# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
    os: ubuntu-lts-latest
    tools:
        python: "3.11"
    commands:
        - pip install uv
        - uv sync
        - uv run mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
