name: Run pytest tests

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Set up Python 3.11
                uses: actions/setup-python@v6
                with:
                    python-version: "3.11"

            -   name: Install uv
                uses: astral-sh/setup-uv@v8
                with:
                    enable-cache: true

            -   name: Lint
                run: uv run ruff check .

            -   name: Install dependencies
                run: uv sync

            -   name: Run pytest
                env:
                    CUSTOMER_NUMBER: ${{ secrets.CUSTOMER_NUMBER }}
                    CONTRACT_ID: ${{ secrets.CONTRACT_ID }}
                    API_KEY: ${{ secrets.API_KEY }}
                run: uv run pytest --tb=short -v